# Site Info
title: 安德魯的部落格
tagline: '安德魯的部落格'
description: '123'

# baseurl: "/lanyon"
baseurl: ""
url: http://columns.chicken-house.net
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
  - jekyll-redirect-from

markdown: kramdown
kramdown:
  input: GFM
#excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 10
paginate_path: '/page:num'
# permalink: pretty
permalink: /:year/:month/:day/:slug/
excerpt_separator: <!--more-->

version: 1.0.0

author:
  name: Andrew Wu
  description: 
#  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/andrew0928
    github:    https://github.com/andrew0928
    facebook:  https://www.facebook.com/andrew.blog.0928
    #twitter:   https://twitter.com/Li_Zhihao
    #weibo:     http://weibo.com/41173780
    #email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=
logo: /public/logo.png

# Navigation (2nd level links supported)
nav:
  Blog:           
    - '/'
    - { Categories: '/categories/' }
    - { Tags: '/tags/' }
  My Codes @ GitHub.com:
    - 'https://github.com/andrew0928'
  About:          
    - '/about/'
  Facebook Pages: 
    - 'https://www.facebook.com/andrew.blog.0928'

# Where are tags and categories displayed
tag_page: '/tags/'
category_page: '/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-68797023-1' # leave blank if you don't want google analytics
disqus_short_name: 'andrew0928' # leave blank if you don't want disqus
